DepremTirProjesi/Models/Malzeme.cs
namespace DepremTirProjesi.Models
{
    public class Malzeme
    {
        public int MalzemeId { get; set; }
        public string MalzemeAd { get; set; }
        public int MalzemeStok { get; set; }
        public int KategoriId { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}

DepremTirProjesi/Controllers/MalzemeController.cs
using DepremTirProjesi.Models;
using DepremTirProjesi.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DepremTirProjesi.Controllers
{
    public class MalzemeController : Controller
    {
        MalzemeRepository malzemeRepository;
        Context c;

        public MalzemeController(MalzemeRepository _malzemeRepository, Context c)
        {
            malzemeRepository = _malzemeRepository;
            this.c = c;
        }

        public IActionResult Index()
        {
            return View(malzemeRepository.TList());
        }

        [HttpGet]
        public IActionResult MalzemeEkle()
        {
            List<SelectListItem> values = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriId.ToString()
                                           }).ToList();

            ViewBag.v1 = values;
            return View();
        }

        [HttpPost]
        public IActionResult MalzemeEkle(Malzeme m)
        {
            
            malzemeRepository.TAdd(m);
            return RedirectToAction("Index");
        }

        public IActionResult MalzemeGet(int id)
        {
            var x = malzemeRepository.TGet(id);

            List<SelectListItem> values = (from y in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = y.KategoriAd,
                                               Value = y.KategoriId.ToString()
                                           }).ToList();

            ViewBag.v1 = values;
            Malzeme m = new Malzeme
            {
                MalzemeId = x.MalzemeId,
                MalzemeAd = x.MalzemeAd,
                KategoriId = x.KategoriId,
                MalzemeStok = x.MalzemeStok,
               
            };

            return View("MalzemeGet", m);
        }

        [HttpPost]
        public IActionResult MalzemeGuncelle(Malzeme m)
        {
            var x = malzemeRepository.TGet(m.MalzemeId);
            x.MalzemeAd = m.MalzemeAd;
            x.MalzemeStok = m.MalzemeStok;
            x.KategoriId = m.KategoriId;

            malzemeRepository.TUpdate(x);


            return RedirectToAction("Index");
        }

    }
}

DepremTirProjesi/Views/Malzeme/Index.cshtml
@model List<DepremTirProjesi.Models.Malzeme>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}

<h1>Index</h1>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Malzeme Ad</th>
        <th>Kategori ID</th>
        <th>Stok</th>
        <th>Delete</th>
        <th>Update</th>
        
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.MalzemeId</td>
            <td>@x.MalzemeAd</td>
            <td>@x.KategoriId</td>
            <td>@x.MalzemeStok</td>
            <td><a href="#" class="btn btn-danger">Delete</a></td>
            <td><a href="/Malzeme/MalzemeGet/@x.MalzemeId" class="btn btn-warning">Guncelle</a></td>
        </tr>
    }

</table>
<a href="/Malzeme/MalzemeEkle/" class="btn btn-primary">Malzeme Ekle</a>

DepremTirProjesi/Views/Malzeme/MalzemeEkle.cshtml
@model DepremTirProjesi.Models.Malzeme

@{
    ViewData["Title"] = "MalzemeEkle";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}

<h1>MalzemeEkle</h1>
<br />

@using (Html.BeginForm("MalzemeEkle", "Malzeme", FormMethod.Post))
{
    @Html.LabelFor(x=>x.MalzemeAd)
    @Html.TextBoxFor(x=>x.MalzemeAd, new{@class="form-control"})
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x=>x.KategoriId,(List<SelectListItem>)ViewBag.v1,new {@class = "form-control"})
    @Html.LabelFor(x=>x.MalzemeStok)
    @Html.TextBoxFor(x=>x.MalzemeStok, new{@class="form-control"})
    <br />

    <button class="btn btn-info">Kaydet</button>

}

DepremTirProjesi/Views/Malzeme/MalzemeGet.cshtml
@model DepremTirProjesi.Models.Malzeme
@{
    ViewData["Title"] = "MalzemeGet";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}

@using (Html.BeginForm("MalzemeGuncelle", "Malzeme", FormMethod.Post))
{
    @Html.LabelFor(x=>x.MalzemeId)
    @Html.TextBoxFor(x=>x.MalzemeId, new{@class="form-control"})
    <br />

    @Html.LabelFor(x=>x.MalzemeAd)
    @Html.TextBoxFor(x=>x.MalzemeAd, new{@class="form-control"})
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x=>x.KategoriId,(List<SelectListItem>)ViewBag.v1,new {@class = "form-control"})
    @Html.LabelFor(x=>x.MalzemeStok)
    @Html.TextBoxFor(x=>x.MalzemeStok, new{@class="form-control"})
    <br />

    <button class="btn btn-info">Kaydet</button>

}