DepremTirProjesi/Models/TirİcerikBilgisi.cs
using System.ComponentModel.DataAnnotations;

namespace DepremTirProjesi.Models
{
    public class TirİcerikBilgisi
    {
        [Key]
        public int TirId { get; set; }
        public string TirPlaka { get; set; }
        public int SehirId { get; set; }
        public virtual Sehir Sehir { get; set; }
        public int IlceId { get; set; }
        public virtual Ilce Ilce { get; set; }
        public int MalzemeId { get; set; }
        public virtual Malzeme Malzeme { get; set; }

    }
}

DepremTirProjesi/Controllers/TirİcerikBilgisiController.cs
using DepremTirProjesi.Models;
using DepremTirProjesi.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace DepremTirProjesi.Controllers
{
    public class TirİcerikBilgisiController : Controller
    {
        TirİcerikBilgisiRepository tirİcerikBilgisiRepository;
        Context c;
        public TirİcerikBilgisiController(TirİcerikBilgisiRepository _tirİcerikBilgisiRepository, Context _c)
        {
            tirİcerikBilgisiRepository = _tirİcerikBilgisiRepository;
            c = _c;
        }
        public IActionResult Index()
        {
            return View(tirİcerikBilgisiRepository.TList());
        }
        [HttpGet]
        public IActionResult TirİcerikBilgisiEkle()
        {
            List<SelectListItem> values1 = (from x in c.Sehirs.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.SehirAdi,
                                                Value = x.SehirId.ToString()
                                            }).ToList();

            ViewBag.v1 = values1;

            List<SelectListItem> values2 = (from y in c.Ilces.ToList()
                                            select new SelectListItem
                                            {
                                                Text = y.IlceAdi,
                                                Value = y.IlceId.ToString()
                                            }).ToList();

            ViewBag.v2 = values2;

            List<SelectListItem> values3 = (from z in c.Malzemes.ToList()
                                            select new SelectListItem
                                            {
                                                Text = z.MalzemeAd,
                                                Value = z.MalzemeId.ToString()
                                            }).ToList();

            ViewBag.v3 = values3;
            return View();
        }

        [HttpPost]
        public IActionResult TirİcerikBilgisiEkle(TirİcerikBilgisi t)
        {

            tirİcerikBilgisiRepository.TAdd(t);
            return RedirectToAction("Index");
        }


        public IActionResult TirİcerikBilgisiGet(int id)
        {
            var x = tirİcerikBilgisiRepository.TGet(id);
            List<SelectListItem> values1 = (from a in c.Sehirs.ToList()
                                            select new SelectListItem
                                            {
                                                Text = a.SehirAdi,
                                                Value = a.SehirId.ToString()
                                            }).ToList();

            ViewBag.v1 = values1;

            List<SelectListItem> values2 = (from y in c.Ilces.ToList()
                                            select new SelectListItem
                                            {
                                                Text = y.IlceAdi,
                                                Value = y.IlceId.ToString()
                                            }).ToList();

            ViewBag.v2 = values2;

            List<SelectListItem> values3 = (from z in c.Malzemes.ToList()
                                            select new SelectListItem
                                            {
                                                Text = z.MalzemeAd,
                                                Value = z.MalzemeId.ToString()
                                            }).ToList();

            ViewBag.v3 = values3;
            TirİcerikBilgisi t = new TirİcerikBilgisi
            {
                TirId= x.TirId,
                TirPlaka = x.TirPlaka,
                SehirId = x.SehirId,
                IlceId = x.IlceId,
                MalzemeId = x.MalzemeId
                

            };
            return View("TirİcerikBilgisiGet", t);
        }

        [HttpPost]
        public IActionResult TirİcerikBilgisiGuncelle(TirİcerikBilgisi t)
        {
            var x = tirİcerikBilgisiRepository.TGet(t.TirId);
            x.TirId = t.TirId;
            x.TirPlaka = t.TirPlaka;
            x.SehirId = t.SehirId;
            x.IlceId = t.IlceId;
            x.MalzemeId = t.MalzemeId;
            tirİcerikBilgisiRepository.TUpdate(x);

            return RedirectToAction("Index");
        }

        public IActionResult TirİcerikBilgisiSil(int id)
        {
            tirİcerikBilgisiRepository.TDelete(new TirİcerikBilgisi { TirId = id });
            return RedirectToAction("Index");
        }
    }
}

DepremTirProjesi/Views/TirİcerikBilgisi/Index.cshtml
@model List<DepremTirProjesi.Models.TirİcerikBilgisi>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}
<h1> Tir İcerik Bilgisi Listesi</h1>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Tır Plaka</th>
        <th>Sehir</th>
        <th>Ilces</th>
        <th>Malzeme</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.TirId</td>
            <td>@x.TirPlaka</td>
            <td>@x.SehirId</td>
            <td>@x.IlceId</td>
            <td>@x.MalzemeId</td>

            <td><a href="/TirİcerikBilgisi/TirİcerikBilgisiSil/@x.TirId" class="btn btn-danger">Delete</a></td>
            <td><a href="/TirİcerikBilgisi/TirİcerikBilgisiGet/@x.TirId/" class="btn btn-success">Update</a></td>
        </tr>
    }
</table>
<a href="/TirİcerikBilgisi/TirİcerikBilgisiEkle/" class="btn btn-primary">Tir İcerik Bilgisi Ekle</a>

DepremTirProjesi/Views/TirİcerikBilgisi/TirİcerikBilgisiEkle.cshtml
@model DepremTirProjesi.Models.TirİcerikBilgisi
@{
    ViewData["Title"] = "TirİcerikBilgisiEkle";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}

<h1>TirİcerikBilgisiEkle</h1>


<br />
@using (Html.BeginForm("TirİcerikBilgisiEkle", "TirİcerikBilgisi", FormMethod.Post))
{
    @Html.Label("Tır Plaka ")
    @Html.TextBoxFor(x=>x.TirPlaka , new{@class="form-control"} )


    <br />
    @Html.LabelFor(x=>x.Sehir.SehirAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.SehirId,(List<SelectListItem>)ViewBag.v1,  new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x=>x.Ilce.IlceAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.IlceId,(List<SelectListItem>)ViewBag.v2,  new { @class = "form-control" })
    <br />

    @Html.LabelFor(x=>x.Malzeme.MalzemeAd,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.MalzemeId,(List<SelectListItem>)ViewBag.v3,  new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
}

DepremTirProjesi/Views/TirİcerikBilgisi/TirİcerikBilgisiGet.cshtml
@model DepremTirProjesi.Models.TirİcerikBilgisi
@{
    ViewData["Title"] = "TirİcerikBilgisiGet";
    Layout = "~/Views/Shared/_ProjeLayout.cshtml";
}

@using (Html.BeginForm("TirİcerikBilgisiGuncelle", "TirİcerikBilgisi", FormMethod.Post))
{
    @Html.Label("Id ")
    @Html.TextBoxFor(x=>x.TirId , new{@class="form-control"} )

    <br />
    @Html.Label("Tır Plaka ")
    @Html.TextBoxFor(x=>x.TirPlaka , new{@class="form-control"} )


    <br />
    @Html.LabelFor(x=>x.Sehir.SehirAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.SehirId,(List<SelectListItem>)ViewBag.v1,  new { @class = "form-control" })
    <br />

    <br />
    @Html.LabelFor(x=>x.Ilce.IlceAdi,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.IlceId,(List<SelectListItem>)ViewBag.v2,  new { @class = "form-control" })
    <br />

    @Html.LabelFor(x=>x.Malzeme.MalzemeAd,new { @class = "form-control" })
    @Html.DropDownListFor(x=>x.MalzemeId,(List<SelectListItem>)ViewBag.v3,  new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
    }